### ISSUE TITLE
Provide easier navigation/multipage structure

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-api-guidelines#52]
Right now the body of the guidelines document is essentially a flat list of guidelines. We should move toward something like mdBook, or some other way of making it easier to navigate and see context.

cc @ubsan

**Comment by ubsan** [comment]
I need to find time to do this... probably next week, unfortunately, I'm working a lot this week.

**Comment by brson** [comment]
Let's please preserve the big checklist though.

**Comment by brson** [comment]
@ubsan still interested in this?

**Comment by aturon** [comment]
@brson this seems like probably a good issue to advertise for the blitz in general.
